### PR TITLE
update k0s asciinema video with a trimmed version

### PR DESCRIPTION
**Pull request by adamparco**

### CODE REVIEW

**Comment by jnummelin** [comment]
The asciicast will not play when opening the page in chrome with e.g. `file:///Users/jussi/code/k0sproject.github.io/index.html`. Some CORS thingy:
```
Access to XMLHttpRequest at 'file:///Users/jussi/code/k0sproject.github.io/videos/k0s_demo_1.cast' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

But seems to work properly when running on localhost with
```
docker run -t -i --rm -v $(pwd)://usr/share/nginx/html -p 8080:80 nginx:1-alpine
```

and then hitting it with `localhost:8080`

**Review by jnummelin — APPROVED** [review]
LGTM.

But I'll let @miskun have the final word, his eyes are more pixel perfect :)

**Comment by miskun** [comment]
Yes, asciinema does not work if page is opened from filesystem but should work otherwise.

**Review by miskun — COMMENTED** [review]
LGTM

**Pull request merged**
